acmpx/urls.py
from django.urls import path
from .views import home, admin

app_name = 'acmpx'
urlpatterns = [
	path('', home.index, name='index'),
	path('certificate/', home.certificate_inquiry, name='certificate_inquiry'),
	path('certificate/<int:certificate_id>/render/', home.certificate_render, name='certificate_render'),
	path('training/<int:training_id>/certificate/render_all/', home.training_certificate_render_all,
		 name='training_certificate_render_all'),
	path('certificate/<int:certificate_id>/show/', home.certificate_show, name='certificate_show'),

	path('admin/', admin.admin_index, name='admin_index'),
	path('admin/login/', admin.admin_login, name='admin_login'),
	path('admin/logout/', admin.admin_logout, name='admin_logout'),
	path('admin/permission_denied/', admin.admin_permission_denied, name='admin_permission_denied'),
	path('admin/training/', admin.admin_training_list, name='admin_training_list'),
	path('admin/training/add/', admin.admin_training_add, name='admin_training_add'),
	path('admin/training/<int:training_id>/edit/', admin.admin_training_edit, name='admin_training_edit'),
	path('admin/training/<int:training_id>/certificate/', admin.admin_certificate_list, name='admin_certificate_list'),
	path('admin/training/<int:training_id>/upload/certificate/', admin.admin_training_upload_certificate,
		 name='admin_training_upload_certificate'),
	path('admin/training/<int:training_id>/download_certificate_set/', admin.admin_training_download_certificate_set,
		 name='admin_training_download_certificate_set'),
	path('admin/training/<int:training_id>/clear_certificate_cache/', admin.admin_training_clear_certificate_cache,
		 name='admin_training_clear_certificate_cache'),
]

version2.0/zhengshu/zhengshu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('acmxs/', include('acmxs.urls')),
]

acmpx/models.py
# coding:utf-8

from django.db import models


class Training(models.Model):
	title = models.CharField('培训名称', max_length=128)
	title_en = models.CharField('培训名称（英文）', max_length=128)
	started_at = models.DateField('培训开始日期')
	ended_at = models.DateField('培训结束日期')
	number_of_participants = models.IntegerField(default=0)
	hidden = models.BooleanField('隐藏', default=False)
	added_at = models.DateTimeField('添加时间', auto_now_add=True)
	updated_at = models.DateTimeField('修改时间', auto_now=True)

	def __str__(self):
		return str(self.id) + ": " + self.title


class Certificate(models.Model):
	id = models.CharField('证书编号', max_length=32, primary_key=True)
	student_no = models.CharField('学号', max_length=32)
	student_class = models.CharField('班级', max_length=32)
	student_name = models.CharField('姓名', max_length=32)
	score = models.IntegerField('分数', default=0)
	rank = models.IntegerField('排名', default=0)
	idx = models.IntegerField('排序索引', default=0)
	training = models.ForeignKey(Training, on_delete=models.CASCADE)

	def __str__(self):
		return self.id + ": " + self.student_class + " " + self.student_name

acmpx/forms.py
# coding:utf-8

from django import forms
from django.forms import ModelForm, TextInput
from .models import Training


class SearchCertificateForm(forms.Form):
	type = forms.ChoiceField(
		label='类型',
		choices=(('student_no', '按学号查询'), ('certificate_no', '按证书编号查询')),
		widget=forms.Select(attrs={'class': 'form-control'})
	)
	query = forms.CharField(
		label='查询内容',
		max_length=128,
		required=False,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '输入查询内容'})
	)


class AdminLoginForm(forms.Form):
	username = forms.CharField(
		label='用户名',
		max_length=128,
		widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '用户名'})
	)
	password = forms.CharField(
		label='密码',
		max_length=128,
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码'})
	)
	next = forms.CharField(label='next', max_length=512, required=False, widget=forms.HiddenInput)


class TrainingForm(ModelForm):
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('label_suffix', '')
		super(TrainingForm, self).__init__(*args, **kwargs)

	class Meta:
		model = Training
		fields = ['title', 'title_en', 'started_at', 'ended_at', 'hidden']
		widgets = {
			'title': TextInput(attrs={'class': 'form-control'}),
			'title_en': TextInput(attrs={'class': 'form-control'}),
			'started_at': TextInput(attrs={'class': 'form-control date-picker'}),
			'ended_at': TextInput(attrs={'class': 'form-control date-picker'}),
		}


class AdminUploadCertificateForm(forms.Form):
	file = forms.FileField()

acmpx/views/admin.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from ..forms import AdminLoginForm, TrainingForm, AdminUploadCertificateForm
from ..models import Training, Certificate
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
import time
import random
import string
import os
from ..modules.XlHandler import XlHandler
from ..modules.CertificateHandler import CertificateHandler


# 后台
@login_required(login_url=settings.ADMIN_LOGIN_URL)
def admin_index(request):
	return render(request, 'acmpx/admin/index.html', {
		'training_count': Training.objects.count(),
		'certificate_count': Certificate.objects.count(),
		'participant_count': Certificate.objects.all().aggregate(Count('student_no', distinct=True))['student_no__count'],
	})


# 后台登录
def admin_login(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect(reverse('acmpx:admin_index'))
	error = None
	if request.method == 'POST':
		form = AdminLoginForm(request.POST)
		if form.is_valid():
			user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
			if user is not None and user.is_active:
				login(request, user)
				if request.POST['next']:
					return HttpResponseRedirect(request.POST['next'])
				else:
					return HttpResponseRedirect(reverse('acmpx:admin_index'))
			else:
				error = '用户名或密码错误'
		else:
			error = '请填写用户名和密码'
	else:
		form = AdminLoginForm()
	return render(request, 'acmpx/admin/login.html', {'form': form, 'error': error})


# 后台登出
def admin_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('acmpx:admin_login'))


# 后台-权限拒绝
@login_required(login_url=settings.ADMIN_LOGIN_URL)
def admin_permission_denied(request):
	return render(request, 'acmpx/admin/permission_denied.html')


# 后台-培训管理
@login_required(login_url=settings.ADMIN_LOGIN_URL)
@permission_required(
	perm=['acmpx.add_training', 'acmpx.change_training', 'acmpx.delete_training'],
	login_url=settings.ADMIN_PERMISSION_DENIED_URL,
)
def admin_training_list(request):
	training_list = Training.objects.all().order_by('id').reverse()
	paginator = Paginator(training_list, 20)
	page = request.GET.get('page')
	try:
		trainings = paginator.page(page)
	except PageNotAnInteger:
		trainings = paginator.page(1)
	except EmptyPage:
		trainings = paginator.page(paginator.num_pages)
	return render(request, 'acmpx/admin/training_list.html', {'item': 'admin_training', 'training_list': trainings})


# 后台-添加培训
@login_required(login_url=settings.ADMIN_LOGIN_URL)
@permission_required(
	perm=['acmpx.add_training'],
	login_url=settings.ADMIN_PERMISSION_DENIED_URL,
)
def admin_training_add(request):
	training_form = TrainingForm()
	errors = list()
	if request.method == 'POST':
		training_form = TrainingForm(request.POST)
		if training_form.is_valid():
			if training_form.cleaned_data['started_at'] > training_form.cleaned_data['ended_at']:
				errors.append('培训开始日期不能晚于培训结束日期')
			else:
				new_training = training_form.save()
				make_training_dir(new_training.id)
				messages.success(request, '添加成功')
				return HttpResponseRedirect(reverse('acmpx:admin_training_list'))
		else:
			for field in training_form:
				for error in field.errors:
					errors.append('{}: {}'.format(field.label, error))
	return render(request, 'acmpx/admin/training_add.html', {
		'item': 'admin_training',
		'form': training_form,
		'errors': errors,
	})


# 后台-添加培训 -> 创建培训相关资源目录
def make_training_dir(training_id):
	training_base_path = settings.MEDIA_ROOT + 'training/' + str(training_id) + '/'
	if not os.path.exists(training_base_path):
		os.makedirs(training_base_path)
	CertificateHandler(training_id).create_certificate_directory()


# 后台-编辑培训
@login_required(login_url=settings.ADMIN_LOGIN_URL)
@permission_required(
	perm=['acmpx.change_training', 'acmpx.delete_training'],
	login_url=settings.ADMIN_PERMISSION_DENIED_URL,
)
def admin_training_edit(request, training_id):
	training = get_object_or_404(Training, pk=training_id)
	training_form = TrainingForm()
	errors = list()
	if request.method == 'GET':
		training_form = TrainingForm(instance=training)
	if request.method == 'POST':
		training_form = TrainingForm(request.POST, instance=training)
		if training_form.is_valid():
			if training_form.cleaned_data['started_at'] > training_form.cleaned_data['ended_at']:
				errors.append('培训开始日期不能晚于培训结束日期')
			else:
				training_form.save()
				messages.success(request, '保存成功 <a href="%s" class="alert-link text-left-gap">点此返回</a>' % reverse(
					'acmpx:admin_training_list'))
				return HttpResponseRedirect(reverse('acmpx:admin_training_edit', args=(training.id,)))
		else:
			for field in training_form:
				for error in field.errors:
					errors.append(field.label + '：' + error)
	return render(request, 'acmpx/admin/training_edit.html', {
		'item': 'admin_training',
		'form': training_form,
		'errors': errors,
		'training_id': training.id,
	})


# 后台-证书管理
@login_required(login_url=settings.ADMIN_LOGIN_URL)
@permission_required(
	perm=['acmpx.add_certificate', 'acmpx.change_certificate', 'acmpx.delete_certificate'],
	login_url=settings.ADMIN_PERMISSION_DENIED_URL,
)
def admin_certificate_list(request, training_id):
	training = get_object_or_404(Training, pk=training_id)
	certificates_list = training.certificate_set.order_by('idx')
	paginator = Paginator(certificates_list, 20)
	page = request.GET.get('page')
	try:
		certificates = paginator.page(page)
	except PageNotAnInteger:
		certificates = paginator.page(1)
	except EmptyPage:
		certificates = paginator.page(paginator.num_pages)
	return render(request, 'acmpx/admin/certificate_list.html', {
		'item': 'admin_training',
		'certificate_list': certificates,
		'training': training,
	})


# 后台-上传证书数据
@login_required(login_url=settings.ADMIN_LOGIN_URL)
@permission_required(
	perm=['acmpx.change_training', 'acmpx.add_certificate', 'acmpx.change_certificate', 'acmpx.delete_certificate'],
	login_url=settings.ADMIN_PERMISSION_DENIED_URL,
)
def admin_training_upload_certificate(request, training_id):
	training = get_object_or_404(Training, pk=training_id)
	if request.method == 'POST':
		form = AdminUploadCertificateForm(request.POST, request.FILES)
		if form.is_valid():
			certificate_data_list = handle_uploaded_certificate(request.FILES['file'])
			if certificate_data_list.has_error:
				messages.error(request, '解析文件时出现严重错误，请检查文件并重新上传')
			else:
				# 上传的表格文件有效，先删除此培训下的所有证书数据，再重新插入数据
				training.certificate_set.all().delete()
				certificate_no_prefix = training.ended_at.strftime('%Y%m%d') + '%04d' % training.id
				for certificate_data in certificate_data_list.info_list:
					Certificate(
						id=certificate_no_prefix + '%04d' % certificate_data.idx,
						student_no=certificate_data.student_no,
						student_class=certificate_data.student_class,
						student_name=certificate_data.student_name,
						score=certificate_data.score,
						rank=certificate_data.rank,
						idx=certificate_data.idx,
						training_id=training.id,
					).save()
				# 更新参与人数
				training.number_of_participants = certificate_data_list.num
				training.save()
				# 删除证书资源文件夹并重建
				CertificateHandler(training.id).delete_all_certificates()
				messages.success(request, '成功导入了 {} 条数据'.format(certificate_data_list.num))
				return HttpResponseRedirect(reverse('acmpx:admin_certificate_list', args=(training.id,)))
		else:
			messages.error(request, '请上传有效的文件')
		return HttpResponseRedirect(reverse('acmpx:admin_training_upload_certificate', args=(training.id,)))
	else:
		form = AdminUploadCertificateForm()
	return render(request, 'acmpx/admin/upload_certificate.html', {'form': form, 'training': training})


# 生成随机字符串
def random_time_based_str():
	return (str(time.time()) + ''.join(random.sample(string.ascii_letters + string.digits, 16))).replace('.', '')


# 后台-上传证书数据 -> 处理上传文件并返回处理好的信息列表
def handle_uploaded_certificate(f):
	random_file_name = random_time_based_str()
	upload_path = settings.MEDIA_ROOT + settings.UPLOAD_TMP_PATH
	if not os.path.exists(upload_path):
		os.makedirs(upload_path)
	file_path = upload_path + random_file_name
	with open(file_path, 'wb+') as destination:
		for chunk in f.chunks():
			destination.write(chunk)
	xl = XlHandler(file_path)
	xl.handle_data()
	os.remove(file_path)
	return xl


# 后台-下载全部证书
@login_required(login_url=settings.ADMIN_LOGIN_URL)
@permission_required(
	perm=['acmpx.add_certificate', 'acmpx.change_certificate', 'acmpx.delete_certificate'],
	login_url=settings.ADMIN_PERMISSION_DENIED_URL,
)
def admin_training_download_certificate_set(request, training_id):
	training = get_object_or_404(Training, pk=training_id)
	# 懒加载，第一次访问时生成证书
	certificate_handler = CertificateHandler(training_id)
	url_list = [settings.BASE_URL + reverse('acmpx:training_certificate_render_all', args=(training.id,))]
	certificate_handler.load_certificate(url_list)
	return HttpResponseRedirect(certificate_handler.get_certificate_url())


# 后台-清除证书缓存
@login_required(login_url=settings.ADMIN_LOGIN_URL)
@permission_required(
	perm=['acmpx.add_certificate', 'acmpx.change_certificate', 'acmpx.delete_certificate'],
	login_url=settings.ADMIN_PERMISSION_DENIED_URL,
)
def admin_training_clear_certificate_cache(request, training_id):
	training = get_object_or_404(Training, pk=training_id)
	CertificateHandler(training_id).delete_all_certificates()
	messages.success(request, '清除证书缓存成功')
	return HttpResponseRedirect(reverse('acmpx:admin_certificate_list', args=(training.id,)))

acmpx/views/home.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from ..forms import SearchCertificateForm
from ..models import Training, Certificate
from django.conf import settings
from ..modules.CertificateHandler import CertificateHandler


# 首页
def index(request):
	return render(request, 'acmpx/index.html')


# 证书查询
def certificate_inquiry(request):
	form = SearchCertificateForm(request.GET)
	certificate_set = None
	if form.is_valid() and form.cleaned_data['query'] != '':
		if form.cleaned_data['type'] == 'student_no':
			certificate_set = Certificate.objects.all().filter(student_no=form.cleaned_data['query'])
		if form.cleaned_data['type'] == 'certificate_no':
			certificate_set = Certificate.objects.all().filter(pk=form.cleaned_data['query'])
	return render(request, 'acmpx/certificate_inquiry.html', {
		'item': 'certificate_inquiry', 'form': form, 'certificate_set': certificate_set
	})


# 证书渲染
def certificate_render(request, certificate_id):
	certificate = get_object_or_404(Certificate, pk=certificate_id)
	return render(request, 'acmpx/certificate_render_a4.html',
				  {'certificate': certificate, 'base_url': settings.BASE_URL})


# 全部证书渲染
def training_certificate_render_all(request, training_id):
	training = get_object_or_404(Training, pk=training_id)
	return render(request, 'acmpx/certificate_render_all_a4.html',
				  {'training': training, 'base_url': settings.BASE_URL})


# 证书查看
def certificate_show(request, certificate_id):
	certificate = get_object_or_404(Certificate, pk=certificate_id)
	# 懒加载，第一次访问时生成证书
	certificate_handler = CertificateHandler(certificate.training_id, certificate_id)
	url_list = [settings.BASE_URL + reverse('acmpx:certificate_render', args=(certificate.id,))]
	certificate_handler.load_certificate(url_list)
	return HttpResponseRedirect(certificate_handler.get_certificate_url())

acmpx/templates/acmpx/admin/certificate_list.html
{% extends 'acmpx/admin/base.html' %}
{% block title %}证书管理{% endblock title %}
{% block content %}
	<div class="container">
		<ol class="breadcrumb">
			<li><a href="{% url 'acmpx:admin_index' %}">后台管理中心</a></li>
			<li><a href="{% url 'acmpx:admin_training_list' %}">培训管理</a></li>
			<li class="active">{{ training.title }} - 证书管理</li>
		</ol>
		<div class="top-action-bar inline-buttons">
			<a class="btn brn-sm btn-primary" role="button"
				 href="{% url 'acmpx:admin_training_upload_certificate' training.id %}">导入数据</a>
			{% if certificate_list %}
				<a class="btn brn-sm btn-default loading-button" role="button"
					 href="{% url 'acmpx:admin_training_download_certificate_set' training.id %}"
					 data-loading-text="加载中，请耐心等待（长时间无响应请刷新重试）">下载全部证书</a>
				<a class="btn brn-sm btn-default loading-button" role="button"
					 href="{% url 'acmpx:admin_training_clear_certificate_cache' training.id %}"
					 data-loading-text="清除缓存中">清除证书缓存</a>
			{% endif %}
		</div>
		<div class="result-list">
			{% if certificate_list %}
				<div class="table-responsive">
					<table class="table table-striped admin-list-table">
						<thead>
						<tr>
							<th>证书编号</th>
							<th>持有者</th>
							<th>分数</th>
							<th>排名</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						{% for certificate in certificate_list %}
							<tr>
								<td>{{ certificate.pk }}</td>
								<td>{{ certificate.student_no }} {{ certificate.student_class }} {{ certificate.student_name }}</td>
								<td>{{ certificate.score }}</td>
								<td>{{ certificate.rank }}/{{ certificate.training.number_of_participants }}</td>
								<td><a href="{% url 'acmpx:certificate_show' certificate.id %}" class="loading-button"
											 data-loading-text="加载中" role="button">查看证书</a></td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>

				<nav aria-label="Page navigation">
					<ul class="pagination pagination-sm admin-list-pagination">
						{#第一页#}
						{% if certificate_list.number > 1 %}
							<li>
								<a href="{% url 'acmpx:admin_certificate_list' training.id %}" aria-label="第一页">
									<span aria-hidden="true">&lt;&lt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&lt;&lt;</span></span>
							</li>
						{% endif %}
						{#上一页#}
						{% if certificate_list.has_previous %}
							<li>
								<a href="{% url 'acmpx:admin_certificate_list' training.id %}?page={{ certificate_list.previous_page_number }}"
									 aria-label="上一页">
									<span aria-hidden="true">&lt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&lt;</span></span>
							</li>
						{% endif %}
						{#当前页#}
						<li class="active">
							<span>第 {{ certificate_list.number }} 页 / 共 {{ certificate_list.paginator.num_pages }} 页</span>
						</li>
						{#下一页#}
						{% if certificate_list.has_next %}
							<li>
								<a href="{% url 'acmpx:admin_certificate_list' training.id %}?page={{ certificate_list.next_page_number }}"
									 aria-label="下一页">
									<span aria-hidden="true">&gt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&gt;</span></span>
							</li>
						{% endif %}
						{#最后一页#}
						{% if certificate_list.number < certificate_list.paginator.num_pages %}
							<li>
								<a href="{% url 'acmpx:admin_certificate_list' training.id %}?page={{ certificate_list.paginator.num_pages }}"
									 aria-label="最后一页">
									<span aria-hidden="true">&gt;&gt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&gt;&gt;</span></span>
							</li>
						{% endif %}
					</ul>
				</nav>
			{% else %}
				<h5>这个培训还没有任何证书</h5>
			{% endif %}
		</div>
	</div>
{% endblock content %}

{#date:"Y 年 m 月 d 日"#}
{#date_en#}

acmpx/templates/acmpx/admin/index.html
{% extends 'acmpx/admin/base.html' %}
{% block title %}后台管理{% endblock title %}
{% block content %}
	<div class="container">
		<div class="jumbotron">
			<h2 class="huge-header">欢迎来到后台管理中心</h2>
			<div class="admin-data-statistics col-sm-6">
				<h4 class="mini-header">数据统计</h4>
				<table>
					<tbody>
					<tr>
						<td class="text-right">累计培训场数：</td>
						<td>{{ training_count }}</td>
					</tr>
					<tr>
						<td class="text-right">累计颁发证书：</td>
						<td>{{ certificate_count }}</td>
					</tr>
					<tr>
						<td class="text-right">累计参与培训人数：</td>
						<td>{{ participant_count }}</td>
					</tr>
					</tbody>
				</table>
			</div>

			<div class="admin-shortcuts col-sm-6">
				<h4 class="mini-header">快速开始</h4>
				<div class="inline-buttons">
					<a class="btn btn-primary btn-lg" href="{% url 'acmpx:admin_training_add' %}" role="button">添加一个培训</a>
					<a class="btn btn-default btn-lg" href="{% url 'acmpx:admin_training_list' %}" role="button">管理所有培训</a>
				</div>
			</div>

			<div class="clearfix"></div>
		</div>
	</div>
{% endblock content %}

acmpx/templates/acmpx/admin/login.html
{% extends 'acmpx/admin/base.html' %}
{% block title %}登录{% endblock title %}
{% block content %}
	{% if error %}
		<div class="message container">
			<div class="alert alert-danger" role="alert">{{ error }}</div>
		</div>
	{% endif %}

	<div class="container">
		<div class="panel panel-default login-panel">
			<div class="panel-body">
				<h4 class="text-center panel-header">后台管理</h4>
				<form action="{% url 'acmpx:admin_login' %}" method="post">
					{% csrf_token %}
					{{ form.next }}
					<div class="form-group">
						{{ form.username }}
					</div>
					<div class="form-group">
						{{ form.password }}
					</div>
					<button type="submit" class="btn btn-block btn-primary">登录</button>
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

acmpx/templates/acmpx/admin/training_add.html
{% extends 'acmpx/admin/training_form.html' %}
{% block title %}添加培训{% endblock title %}
{% block form_url %}{% url 'acmpx:admin_training_add' %}{% endblock %}
{% block current_position %}添加培训{% endblock %}
{% block form_submit %}添加{% endblock %}

acmpx/templates/acmpx/admin/training_list.html
{% extends 'acmpx/admin/base.html' %}
{% load acmpx_extras %}
{% block title %}培训管理{% endblock title %}
{% block content %}
	<div class="container">
		<ol class="breadcrumb">
			<li><a href="{% url 'acmpx:admin_index' %}">后台管理中心</a></li>
			<li class="active">培训管理</li>
		</ol>

		<div class="top-action-bar inline-buttons">
			<a class="btn brn-sm btn-primary" role="button" href="{% url 'acmpx:admin_training_add' %}">添加培训</a>
		</div>
		<div class="result-list">
			{% if training_list %}
				<div class="table-responsive">
					<table class="table table-striped admin-list-table">
						<thead>
						<tr>
							<th></th>
							<th>ID</th>
							<th>培训名称</th>
							<th>培训开始日期</th>
							<th>培训结束日期</th>
							<th>参加人数</th>
							<th>操作</th>
						</tr>
						</thead>
						<tbody>
						{% for training in training_list %}
							<tr>
								{% if training.hidden %}
									<td class="text-red text-bold">已隐藏</td>
								{% else %}
									<td></td>
								{% endif %}
								<td>{{ training.id }}</td>
								<td>{{ training.title }}</td>
								<td>{{ training.started_at|date:"Y-m-d" }}</td>
								<td>{{ training.ended_at|date:"Y-m-d" }}</td>
								<td>{{ training.number_of_participants }}</td>
								<td>
									<a href="{% url 'acmpx:admin_training_edit' training.id %}">编辑</a>
									<a class="text-left-gap" href="{% url 'acmpx:admin_certificate_list' training.id %}">管理证书</a>
								</td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>

				<nav aria-label="Page navigation">
					<ul class="pagination pagination-sm admin-list-pagination">
						{#第一页#}
						{% if training_list.number > 1 %}
							<li>
								<a href="{% url 'acmpx:admin_training_list' %}" aria-label="第一页">
									<span aria-hidden="true">&lt;&lt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&lt;&lt;</span></span>
							</li>
						{% endif %}
						{#上一页#}
						{% if training_list.has_previous %}
							<li>
								<a href="{% url 'acmpx:admin_training_list' %}?page={{ training_list.previous_page_number }}"
									 aria-label="上一页">
									<span aria-hidden="true">&lt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&lt;</span></span>
							</li>
						{% endif %}
						{#当前页#}
						<li class="active">
							<span>第 {{ training_list.number }} 页 / 共 {{ training_list.paginator.num_pages }} 页</span>
						</li>
						{#下一页#}
						{% if training_list.has_next %}
							<li>
								<a href="{% url 'acmpx:admin_training_list' %}?page={{ training_list.next_page_number }}"
									 aria-label="下一页">
									<span aria-hidden="true">&gt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&gt;</span></span>
							</li>
						{% endif %}
						{#最后一页#}
						{% if training_list.number < training_list.paginator.num_pages %}
							<li>
								<a href="{% url 'acmpx:admin_training_list' %}?page={{ training_list.paginator.num_pages }}"
									 aria-label="最后一页">
									<span aria-hidden="true">&gt;&gt;</span>
								</a>
							</li>
						{% else %}
							<li class="disabled">
								<span><span aria-hidden="true">&gt;&gt;</span></span>
							</li>
						{% endif %}
					</ul>
				</nav>
			{% else %}
				<h5>现在还没有任何培训</h5>
			{% endif %}
		</div>
	</div>
{% endblock content %}